### ISSUE TITLE
Constants being placed in Class Variables region

### ISSUE THREAD

**Issue by rithinch** [vtkhanh/PinnacleCodingConvention#12]
Nice one for the extension @vtkhanh. :thumbsup:

While using it I've come across the following issue:

Currently, all **constants** are being placed in **class variables** region. 

For example, consider the following class.

```csharp
    region MyClass
    public class MyClass
    {
        #region Constants...
        private const string MY_CONSTANT = "\r\n";
        private const string MY_CONSTANT_2 = ",";
        #endregion

        #region Class Variables...
        private string __MyClassVariable;
        #endregion
    }
```

Running the extension currently produces the following output:

```csharp
    #region MyClass

    #region : MyClass :
    public class MyClass
    {

        #region Class Variable(s)...
        private const string MY_CONSTANT = "\r\n";
        private const string MY_CONSTANT_2 = ",";

        private string __MyClassVariable;
        #endregion

    }
    #endregion
```

We would need to distinguish constants+class variables and add them in seperate regions. 

Additionally, the existing class region `MyClass` remains as it is on top and a new class name region is added `: MyClass: `. Either we could remove the existing one or update it to be new name.

Let me know if I can contribute to this. :smiley:

**Comment by vtkhanh** [comment]
Hi,

First of all, thank you so much for reporting the issue :).

The reason why const & variables are grouped together is because some team is following this style where const & variable belongs to one group only. @minhkuoc  is helping to add an Setting so that it allows to toggle between 2 styles, same group or 2 groups of regions.

I could not reproduce the issue with `class` region. As I see in the example, you lack of the `endregion` for the `class`. Is that the reason?

I'd be love to have your contribution, but at this stage when the code is not really finalized, and I'm planning to make some refactoring so think it's best to let me tackle on the issues. Just don't want you to spend time to understand how it works and then it is changed.

**Comment by rithinch** [comment]
@vtkhanh, yes ignore that then; the `class` region might be because of missing `endregion`.

Also, it would be cool to automatically remove and sort using statements when the extension is run👍 

I'll close this issue if constants separation is already being looked into.

**Comment by vtkhanh** [comment]
@rithinch Thanks for your suggestion. That's a good idea. I will put it in the extension soon.
